import Image from 'next/image'
import Button from '@mui/material/Button'

import { Head } from '../src/components/shared/Head'

export default function Home() {
  return (
    <div>
      <Head
        title="Create Next App"
        description="Generated by create next app"
        icon="/favicon.ico"
      />

      <main>
        <Button>Jonas</Button>
      </main>
    </div>
  )
}
